name: Build and Cypress test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json

        - name: Install dependencies
          run: npm install

        - name: Build app
          run: npm run build

        - name: Run tests
          run: npm run cypress:component:run